runtime:
  cache_dir: ./.cache/antora

site:
  title: Tekton Tutorial
  url: https://redhat-scholars.github.io/tekton-tutorial
  start_page: tekton-tutorial::index.adoc
content:
  sources:
    - url: .
      branches: HEAD
      start_path: documentation

asciidoc:
  attributes:
    tutorial-namespace: tektontutorial
    kubernetes-version: v1.23.3
    release-version: master
    page-pagination: true
    tekton-version: v0.24.3
    triggers-version: v0.14.2
    kn-version: v0.17.3
    tekton-cli-version: 0.19.0
    cli: kubectl
    openshift-version: 4.8
    kind-version: v0.9.0
    minikube-version: v1.25.0
    tutorial-apps-revision: master
    workshop-domain: guru.devx.red
    openshift-console-url: https://console-openshift-console.apps.example.com
    etherpad-url: http://example.com
  extensions:
    - ./lib/remote-include-processor.js
    - ./lib/tab-block.js
ui:
  bundle:
    url: https://github.com/redhat-developer-demos/rhd-tutorial-ui/releases/download/v0.1.9/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

output:
  dir: ./gh-pages
