apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: git-clone-
  labels:
    tekton.dev/task: git-clone
spec:
  taskRef:
    name: git-clone
  params:
    - name: url
      value: https://github.com/redhat-scholars/tekton-tutorial-greeter
    - name: revision
      value: master
    - name: deleteExisting
      value: 'true'
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: tekton-tutorial-sources
