---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: greeter
spec:
  virtualhost:
    fqdn: greeter.127.0.0.1.nip.io
  routes:
    - conditions:
      - prefix: /
      services:
        - name: greeter
          port: 8080